// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package sqlc

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    name,
    email
) VALUES (
    $1,
    $2
)
RETURNING id, name, email
`

type CreateFileParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile, arg.Name, arg.Email)
	var i File
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, name, email FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getFiles = `-- name: GetFiles :many
SELECT id, name, email FROM files
`

func (q *Queries) GetFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
