// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type File struct {
	ID    int32
	Name  string
	Email string
}

type User struct {
	ID    int32
	Name  string
	Email string
}
